### ISSUE TITLE
Fallback to database query if redis connection fails

### ISSUE THREAD

**Issue by rr-philips-effah** [ebean-orm/ebean-redis#10]
Currently, if application redis connection fails, ebean-redis does not fallback to database query. Cache is secondary data so failure to retrieve it should not fail the query with cache.

**Comment by rbygrave** [comment]
I'd need to see the stack trace.  Do you have it?   

Also just noting that technically we should probably create issues in the github/ebean-orm/ebean project as that is now where the ebean-redis code is.  This repo was deprecated when we moved the ebean-redis code there.

**Comment by rbygrave** [comment]
Dang, this got left.  I suspect this is in calling DefaultServer.findIdCheckPersistenceContextAndCache()

**Comment by rbygrave** [comment]
Moved to https://github.com/ebean-orm/ebean/issues/2323

Closing this one.
