### ISSUE TITLE
No Configuration of redis password

### ISSUE THREAD

**Issue by yuangu** [ebean-orm/ebean-redis#3]
add config  ebean.redis.auth ?

**Comment by ZL0520** [comment]
* 可以通过覆盖 io.ebean.redis.RedisConfig 的方式解决问题 在createPool() 方法中找到JedisPool带密码的构造函数即可。

**Comment by rbygrave** [comment]
Sorry, is this still an issue?  I don't think I understand clearly.  Thanks.

**Comment by rbygrave** [comment]
Also note that we are likely to move ebean-redis into the ebean project as a module.

**Comment by yuangu** [comment]
sorry for my poor english.  Can   ebean-redis  connect to redis with  password? And  how to config it?

**Comment by rbygrave** [comment]
In RedisCacheFactory we have `JedisPool jedisPool = config.getServiceObject(JedisPool.class);`:

```java
  /**
   * Return the JedisPool to use (only 1 at this stage).
   */
  private JedisPool getJedisPool(DatabaseConfig config) {
    JedisPool jedisPool = config.getServiceObject(JedisPool.class);
    if (jedisPool != null) {
      return jedisPool;
    }
    RedisConfig redisConfig = config.getServiceObject(RedisConfig.class);
    if (redisConfig == null) {
      redisConfig = new RedisConfig();
    }
    redisConfig.loadProperties(config.getProperties());
    log.info("using l2cache redis host {}:{}", redisConfig.getServer(), redisConfig.getPort());
    return redisConfig.createPool();
  }
```

At the moment we need to externally create the `JedisPool` using one of the constructors that takes the username and password as arguments to the constructor.  We then need to set this via `databaseConfig.putServiceObject(...)` so something like:

```java

DatabaseConfig config = new DatabaseConfig();
...
JedisPool jedisPool = ...; // create with username and password etc
config.putServiceObject(jedisPool)

Database database = DatabaseFactory.create(config);
```

Does that make sense?

At the moment we are not able to configure the username and password via `io.ebean.redis.RedisConfig`.  We could/should look to modify this and modify it's `createPool()` method such that if the username/password is set it uses a different JedisPool constructor (that takes the configured username/password).

**Comment by rbygrave** [comment]
Ok, making the change to RedisConfig to additionally support 
- username (default null)
- password (default null)
- timeout (default 2000)
- ssl (default false)

So we can now just configure password, username, timeout and ssl via properties.

### Example
```properties 
ebean.redis.password=mysecret
```

### Example
```properties 
ebean.redis.username=myuser
ebean.redis.password=mysecret
```

### Example

```properties 
ebean.redis.username=myuser
ebean.redis.password=mysecret
ebean.redis.timeout=3000
ebean.redis.ssl=true
```
